badges:
  - npm/v
  - runkit
  - id: github/workflow/status
    to: https://github.com/agorischek/jest-joi/actions/workflows/ci.yml
  - codecov/c
  - github/license
  - badge-roll

settings:
  position: below-lead
  separator: newline

about:
  branch: main
  workflow: CI
