badges:
  - npm/v
  - runkit
  - github/actions/workflow/status
  - codecov/c
  - github/license
  - badge-roll

settings:
  position: current
  separator: newline

about:
  branch: main
  workflow: .github/workflows/ci.yml
